### ISSUE TITLE
gotoassignment tests are giving error

### ISSUE THREAD

**Issue by onur** [vheon/JediHTTP#26]
Hi. I am maintainer of vim-youcompleteme/ycmd packages for Debian and Ubuntu. I am trying to update packages to latest version but some tests are giving error for some reason with a message: `goto_assignments() takes exactly 1 argument (2 given)`

Do you have any idea what is causing this error?

I am using JediHTTP 33082a3. Full output:

```
#1 jedihttp.tests.handlers_test.test_healthy ... ok
#2 jedihttp.tests.handlers_test.test_ready ... ok
#3 jedihttp.tests.handlers_test.test_completion ... ok
#4 jedihttp.tests.handlers_test.test_py3 ... SKIP: Python 3.x only test
#5 jedihttp.tests.handlers_test.test_good_gotodefinition ... ok
#6 jedihttp.tests.handlers_test.test_bad_gotodefinitions_blank_line ... ok
#7 jedihttp.tests.handlers_test.test_bad_gotodefinitions_not_on_valid_position ... ok
#8 jedihttp.tests.handlers_test.test_good_gotoassignment ... ERROR
#9 jedihttp.tests.handlers_test.test_good_gotoassignment_do_not_follow_imports ... ERROR
#10 jedihttp.tests.handlers_test.test_good_gotoassignment_follow_imports ... ERROR
#11 jedihttp.tests.handlers_test.test_usages ... ok
#12 jedihttp.tests.end_to_end_test.test_client_bad_request_with_parameters ... ok
#13 jedihttp.tests.end_to_end_test.test_client_python3_specific_syntax_completion ... ok
#14 jedihttp.tests.end_to_end_test.test_client_request_with_parameters ... ok
#15 jedihttp.tests.end_to_end_test.test_client_request_without_parameters ... ok

======================================================================
ERROR: jedihttp.tests.handlers_test.test_good_gotoassignment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/tests/handlers_test.py", line 144, in test_good_gotoassignment
    request_data ).json[ 'definitions' ]
  File "/usr/lib/python2.7/dist-packages/webtest/utils.py", line 36, in wrapper
    return self._gen_request(method, url, **kw)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 740, in _gen_request
    expect_errors=expect_errors)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 636, in do_request
    self._check_status(status, res)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 668, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/gotoassignment)
'{"exception": {"TYPE": "TypeError"}, "traceback": "Traceback (most recent call last):\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 862, in _handle\\n    return route.call(**args)\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 1740, in wrapper\\n    rv = callback(*a, **ka)\\n  File \\"$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/handlers.py\\", line 91, in gotoassignments\\n    response = _FormatDefinitions( script.goto_assignments( follow_imports ) )\\nTypeError: goto_assignments() takes exactly 1 argument (2 given)\\n", "message": "goto_assignments() takes exactly 1 argument (2 given)"}'
-------------------- >> begin captured logging << --------------------
jedihttp.handlers: DEBUG: received /gotoassignment request
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: jedihttp.tests.handlers_test.test_good_gotoassignment_do_not_follow_imports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/tests/handlers_test.py", line 181, in test_good_gotoassignment_do_not_follow_imports
    request_data ).json[ 'definitions' ]
  File "/usr/lib/python2.7/dist-packages/webtest/utils.py", line 36, in wrapper
    return self._gen_request(method, url, **kw)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 740, in _gen_request
    expect_errors=expect_errors)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 636, in do_request
    self._check_status(status, res)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 668, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/gotoassignment)
'{"exception": {"TYPE": "TypeError"}, "traceback": "Traceback (most recent call last):\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 862, in _handle\\n    return route.call(**args)\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 1740, in wrapper\\n    rv = callback(*a, **ka)\\n  File \\"$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/handlers.py\\", line 91, in gotoassignments\\n    response = _FormatDefinitions( script.goto_assignments( follow_imports ) )\\nTypeError: goto_assignments() takes exactly 1 argument (2 given)\\n", "message": "goto_assignments() takes exactly 1 argument (2 given)"}'
-------------------- >> begin captured logging << --------------------
jedihttp.handlers: DEBUG: received /gotoassignment request
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: jedihttp.tests.handlers_test.test_good_gotoassignment_follow_imports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/tests/handlers_test.py", line 208, in test_good_gotoassignment_follow_imports
    request_data ).json[ 'definitions' ]
  File "/usr/lib/python2.7/dist-packages/webtest/utils.py", line 36, in wrapper
    return self._gen_request(method, url, **kw)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 740, in _gen_request
    expect_errors=expect_errors)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 636, in do_request
    self._check_status(status, res)
  File "/usr/lib/python2.7/dist-packages/webtest/app.py", line 668, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/gotoassignment)
'{"exception": {"TYPE": "TypeError"}, "traceback": "Traceback (most recent call last):\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 862, in _handle\\n    return route.call(**args)\\n  File \\"/usr/lib/python2.7/dist-packages/bottle.py\\", line 1740, in wrapper\\n    rv = callback(*a, **ka)\\n  File \\"$YCMD_DIR/ycmd/third_party/JediHTTP/jedihttp/handlers.py\\", line 91, in gotoassignments\\n    response = _FormatDefinitions( script.goto_assignments( follow_imports ) )\\nTypeError: goto_assignments() takes exactly 1 argument (2 given)\\n", "message": "goto_assignments() takes exactly 1 argument (2 given)"}'
-------------------- >> begin captured logging << --------------------
jedihttp.handlers: DEBUG: received /gotoassignment request
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 15 tests in 0.596s

FAILED (SKIP=1, errors=3)
```

**Comment by onur** [comment]
Ok I found the error. Looks like JediHTTP requires a recent jedi than 0.9.0: `follow_imports` is only available in git repository: https://github.com/davidhalter/jedi/blob/a51475d265fab0361c35608a3204dbbd0c5a1df8/jedi/api/__init__.py#L199

**Comment by vheon** [comment]
JediHTTP is tested for a specific version of jedi and it is for that reason that I have jedi as a git submodule in the `vendor` directory.
